import { Product, Client, Order } from './types';

export const MOCK_PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Smartwatch Series X',
    category: 'Eletrônicos',
    purchase_price: 899.3,
    sale_price: 1299.00,
    price: 1299.00,
    stock: 24,
    description: 'Relógio inteligente moderno branco e minimalista.',
    image: 'https://picsum.photos/seed/watch/400/400',
    available: true,
    unidade_medida: 'un',
    quantidade_unidade: 1,
    controla_estoque: true,
  },
  {
    id: '2',
    name: 'Headphone Noise Cancelling',
    category: 'Eletrônicos',
    purchase_price: 590.00,
    sale_price: 850.00,
    price: 850.00,
    stock: 8,
    description: 'Fones de ouvido bluetooth pretos profissionais.',
    image: 'https://picsum.photos/seed/headphone/400/400',
    available: true,
    unidade_medida: 'un',
    quantidade_unidade: 1,
    controla_estoque: true,
  },
  {
    id: '3',
    name: 'Tablet Pro 11\' 256GB',
    category: 'Eletrônicos',
    purchase_price: 3213.00,
    sale_price: 4590.00,
    price: 4590.00,
    stock: 15,
    description: 'Tablet cinza com caneta stylus ao lado.',
    image: 'https://picsum.photos/seed/tablet/400/400',
    available: true,
    unidade_medida: 'un',
    quantidade_unidade: 1,
    controla_estoque: true,
  },
  {
    id: '4',
    name: 'Câmera Mirrorless 4K',
    category: 'Fotografia',
    purchase_price: 4340.00,
    sale_price: 6200.00,
    price: 6200.00,
    stock: 0,
    description: 'Câmera fotográfica vintage profissional preta.',
    image: 'https://picsum.photos/seed/camera/400/400',
    available: false,
    unidade_medida: 'un',
    quantidade_unidade: 1,
    controla_estoque: true,
  },
];

export const MOCK_CLIENTS: Client[] = [
  {
    id: '1',
    name: 'João Silva',
    establishment: 'Mercado Esperança',
    phone: '(11) 98765-4321',
    whatsapp: '(11) 98765-4321',
    address: 'Rua das Flores, 123',
    city: 'São Paulo - SP',
    observations: 'Cliente preferencial.',
    active: true,
  },
  {
    id: '2',
    name: 'Maria Oliveira',
    establishment: 'Restaurante Sabor Real',
    phone: '(11) 91234-5678',
    whatsapp: '(11) 91234-5678',
    address: 'Av. Paulista, 1500',
    city: 'São Paulo - SP',
    observations: 'Entrega somente no período da manhã.',
    active: true,
  },
  {
    id: '3',
    name: 'Ricardo Santos',
    establishment: 'Café Central',
    phone: '(11) 97777-8888',
    whatsapp: '(11) 97777-8888',
    address: 'Rua Augusta, 900',
    city: 'São Paulo - SP',
    observations: '',
    active: true,
  },
];

export const MOCK_ORDERS: Order[] = [
  {
    id: '89231',
    clientId: '1',
    clientName: 'Supermercado Alvorada',
    date: 'Hoje, 09:45',
    items: [{ productId: '1', quantity: 3, price: 1299.00 }],
    total: 4250.00,
    status: 'delivered',
  },
  {
    id: '89230',
    clientId: '2',
    clientName: 'Mini Mercado Central',
    date: 'Hoje, 08:30',
    items: [{ productId: '2', quantity: 2, price: 850.00 }],
    total: 1890.00,
    status: 'pending',
  },
  {
    id: '89229',
    clientId: '3',
    clientName: 'Padaria Pão de Mel',
    date: 'Ontem, 17:15',
    items: [{ productId: '3', quantity: 1, price: 750.00 }],
    total: 750.00,
    status: 'delivered',
  },
  {
    id: '89228',
    clientId: '1',
    clientName: 'Mercado do Bairro',
    date: 'Ontem, 14:20',
    items: [{ productId: '1', quantity: 2, price: 1200.00 }],
    total: 2400.00,
    status: 'cancelled',
  },
];
